stages:
  - build
  - publish

variables:
  NODE_VERSION: '22'

default:
  image: node:${NODE_VERSION}
  before_script:
    - yarn install --frozen-lockfile

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist
      - package.json
      - yarn.lock
  only:
    - tags

publish:
  stage: publish
  needs:
    - build
  before_script: []
  id_tokens:
    NPM_ID_TOKEN:
      aud: "npm:registry.npmjs.org"
  script:
    # 1) обновляем npm до свежего
    - npm install -g npm@latest
    - npm -v

    # 2) проверяем, что GitLab реально выдал OIDC-токен для npm
    - 'if [ -z "$NPM_ID_TOKEN" ]; then echo "NPM_ID_TOKEN is EMPTY — OIDC не выдался"; exit 1; else echo "NPM_ID_TOKEN is present"; fi'

    # 3) публикация с provenance (триггерит trusted publisher)
    - NPM_CONFIG_PROVENANCE=true npm publish --access public
  only:
    - tags
